### ISSUE TITLE
2nd Arg isnt the target

### ISSUE THREAD

**Issue by Hexer10** [b3none/vip-adder#1]
https://github.com/b3none/vip-adder/blob/a12724c11c6f0142df7bc5d769c673b69f2cf111/scripting/vip-adder.sp#L111

Since that is a Cmd Handler the second arg is the arg count, it cannot be the target, you shoud use:
https://sm.alliedmods.net/new-api/helpers/FindTarget 
or
https://sm.alliedmods.net/new-api/commandfilters/ProcessTargetString (For multi targets)
to get the target(s)

Also Idk if it's your means, but that VIP isnt sure that will stay until the map end, to do that you should ressing the flags using:
https://sm.alliedmods.net/new-api/admin/OnRebuildAdminCache
Because the flags build be removed when the amministrators get reloaded.

**Comment by B3none** [comment]
I'll look into that when I get chance, thanks for the feedback.

-- Alex

**Comment by B3none** [comment]
2 years isn't too late to have solved this, right? 🥇
